### ISSUE TITLE
Better explanation of app

### ISSUE THREAD

**Issue by candroid-man** [SanmerApps/PI#102]
I keep seeing this on F-Droid, and I know that this app replaces the AOSP package installer, but what i want to know is why. Why does Pi exist? What is the use case?

**Comment by candroid-man** [comment]
I hope I didn't come off as rude. I just think you should add some sort of description of the app to GitHub and F-Droid so people know what it is, because I still have no clue what this app does

**Comment by SanmerDev** [comment]
This is an experimental project. Although this app can be used normally, this does not mean that I will consider the needs of users. So, I have not added any description.

**Comment by plenusred** [comment]
Why won't you or anyone step forward and write a bit about it? Pretty simple to understand and explain I'd say. @SanmerDev would you kindly consider reopening as **good first issue**?
