### ISSUE TITLE
app description and screenshots?

### ISSUE THREAD

**Issue by IzzySoft** [SanmerApps/PI#12]
Is there a more detailed description plus some screenshots of the app? I'm considering adding it to [my repo](https://apt.izzysoft.de/fdroid), and would need those for this. Thanks in advance!

**Comment by SanmerDev** [comment]
As written in the README, PI is short for Package Installer, so it is just a Package Installer and its function is very simple.

I need it so I wrote it, but I probably won't spend much time maintaining it. In short, my idea is, this app works for me, you can use it if you like, but if you need features that I don't need, then I won't add them.

So I want it to be a niche project 😋.

**Comment by IzzySoft** [comment]
So you don't want me to provide it via my repo then? No offense taken, just asking.

**Comment by SanmerDev** [comment]
You can, after all, it is an open source project. 

But there won’t be more info on the README 😶‍🌫️.

**Comment by IzzySoft** [comment]
I still don't get how it's working. It allows to authorize applications for … being able to install apps? What is the difference to enabling them in "unknown sources"? The app runs a service, and you can define an "installation requester". So I assume PI uses root/Shizuku to perform installs (and thus does not need to be enabled via "unknown sources"), and its service would capture install attempts from authorized apps and routes them through. Is that correct? So it's basically a replacement to Android's own "unknown sources" configuration?

**Comment by moriel5** [comment]
I second this question.

I have no issues with your intention, however currently it's documentation makes no sense regarding the app's functionality.
