### ISSUE TITLE
not issue but see

### ISSUE THREAD

**Issue by trindadedev13** [SanmerApps/PI#180]
I have a question, where do you find the icons used in your applications? I think they are beautiful

**Comment by DerGoogler** [comment]
@trindadedev13 

Are you lazy? 
https://github.com/SanmerApps/PI?tab=readme-ov-file#credits

**Comment by trindadedev13** [comment]
> @trindadedev13
> 
> Are you lazy? https://github.com/SanmerApps/PI?tab=readme-ov-file#credits


calm down my dear
