### ISSUE TITLE
Ability to install apps with api 23 or lower (android 6)

### ISSUE THREAD

**Issue by NeverSm1le** [SanmerApps/PI#36]
Would you consider adding the ability to install api23 or lower apps on android 14? The other way around is to use adb.

**Comment by SanmerDev** [comment]
How to achieve this? I have no idea about it 🤔.

**Comment by NeverSm1le** [comment]
> How to achieve this? I have no idea about it 🤔.

Do your app use adb to install apks? If yes then you can add --bypass-low-target-sdk-block flag on install

**Comment by NeverSm1le** [comment]
Thank you for adding this!
