### ISSUE TITLE
Stuck on Installing

### ISSUE THREAD

**Issue by cyberastr4l** [SanmerApps/PI#37]
After I allow my file Explorer to install an app a notification appear saying it is installing the app. The notification doesn't disappear and the app doesn't install, I've been waiting for more than 5 minutes. I'm using the shizuku mode and shizuku is running. 

My device is a Samsung S21 5G running Android 14 One UI 6.0

**Comment by SanmerDev** [comment]
Is it adb mode? 
If so, you can try this ci version 4726715d7d4baa421a584fefd0b815b4b7314d02.

**Comment by cyberastr4l** [comment]
This is what the app looks like when shizuku is running. ![Screenshot_20240226_115520_PI.jpg](https://github.com/SanmerApps/PI/assets/140955525/1ab3b481-334e-40b9-bef9-03661ffa8726)

**Comment by SanmerDev** [comment]
Yes, this issue has been solved in 4726715d7d4baa421a584fefd0b815b4b7314d02.
