### ISSUE TITLE
ERROR Pl keeps stopping when I try to install an apk

### ISSUE THREAD

**Issue by akrram0** [SanmerApps/PI#59]
Pl running using shizuku
Android 13
Coloros13
Oppo a74
![Screenshot_2024-04-21-07-37-01-53_29c0a1e3aaa5223e1ffcd3f9ab52a346](https://github.com/SanmerApps/PI/assets/140515513/c760198b-36cc-41e5-8bc4-1080977dc939)

**Comment by SA9990** [comment]
Hello
I'm also facing this issue, it was fine until the latest release.
I'm attaching a Log
[PI.zip](https://github.com/SanmerApps/PI/files/15050955/PI.zip)

**Comment by SA9990** [comment]
Thanks for the response, issue resolved
