### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: column '_display_name' does not exist

### ISSUE THREAD

**Issue by lesar8** [SanmerApps/PI#62]
Hello, the issue from ticket #59 is still occurs on Android 10 when using v0.3.7 and v0.3.8, v0.3.6 is the last version that works.

My phone is Samsung A10s non-rooted running Shizuku.

**Comment by SanmerDev** [comment]
Please upload logs, otherwise there is no way to deal with it.

**Comment by lesar8** [comment]
Today I learned Logcat and it's not fun :-( Anyway here is the log file.
[Logcat.txt](https://github.com/SanmerApps/PI/files/15081661/Logcat.txt)

**Comment by SanmerDev** [comment]
From logs, this has nothing to do with #59. And, there is no useful info in logs you provided.
> You can try to install a apk while running `logcat` to ensure that you can get valid logs.

**Comment by lesar8** [comment]
Hello, I figured out the PID of "dev.sanmer.pi" on my device is 19232. But when I type `adb shell logcat --pid=19232`, it only records for couples of seconds and then terminate the ADB, basically impossible to wait until i install the APK file. With other apps, this command works so i'm not sure why.

I have no choice but record all the operations by this command `adb shell logcat -f /mnt/sdcard/logcat.txt`. The log size is 9 MB, just search for the string "19232" to locate the "PI" process.

**Comment by SanmerDev** [comment]
You can try [PI-0.3.8.dev.fb3ab9a-205-release](https://github.com/SanmerApps/PI/actions/runs/8819305845/artifacts/1443871881)

**Comment by lesar8** [comment]
> You can try [PI-0.3.8.dev.fb3ab9a-205-release](https://github.com/SanmerApps/PI/actions/runs/8819305845/artifacts/1443871881)

Unfortunately it still crashes, but I figured out how to record the log files for "PI" by using this command `adb shell logcat --pid=30228 -f /mnt/sdcard/logcat.txt` (the PID number changed when remove and install again)

Here is the log, only 15 KB !
[logcat.txt](https://github.com/SanmerApps/PI/files/15097095/logcat.txt)
