### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: column '_display_name' does not exist

### ISSUE THREAD

**Issue by lesar8** [SanmerApps/PI#64]
> > You can try [PI-0.3.8.dev.fb3ab9a-205-release](https://github.com/SanmerApps/PI/actions/runs/8819305845/artifacts/1443871881)
> 
> Unfortunately it still crashes, but I figured out how to record the log files for "PI" by using this command `adb shell logcat --pid=30228 -f /mnt/sdcard/logcat.txt` (the PID number changed when remove and install new version)
> 
> Here is the log, only 15 KB ! [logcat.txt](https://github.com/SanmerApps/PI/files/15097095/logcat.txt)

**Comment by SanmerDev** [comment]
This problem can't be reproduced, and PI works fine in Emulated(Android 10)
