### ISSUE TITLE
Can't install APK files using PI

### ISSUE THREAD

**Issue by Aybinx** [SanmerApps/PI#65]
I installed this coz I think it's great package installer but it always says " Install failed " for apk files

[Screenshot](https://ibb.co/myBLQfv)

**Comment by Sudhanshu074w** [comment]
I'm not able to install apps.  I've attached the problem which I'm facing. 

https://github.com/SanmerApps/PI/assets/135090647/7f87c0f5-a491-490f-a802-c2d726bdd75f

**Comment by SanmerDev** [comment]
@Sudhanshu074w A video is useless, please provide logs.

**Comment by SanmerDev** [comment]
Do not reopen this issue until there is a useful log.

**Comment by JFMugen** [comment]
@SanmerDev Hey there, I am having the same issue as well with Shizuku. It just gives Install Failed error. 

I am willing to give a log file but I couldn't find any option in the app options etc. that gives me a log.
