### ISSUE TITLE
App not working properly

### ISSUE THREAD

**Issue by Sudhanshu074w** [SanmerApps/PI#66]
Hello Dev, Greetings !
I want to mention an issue with the Package Installer (PI) app in which the installation dialogue doesn't appear. It just shows the loading screen and closes instantly. I've authorised all apps and gave root permissions to the app. I've attached the logs, please have a look.
[27_04-10-34-28_394.log](https://github.com/SanmerApps/PI/files/15137098/27_04-10-34-28_394.log)
 If there's any error in log-taking, then please guide me. I'll send logs again.

**Comment by SanmerDev** [comment]
There are no errors in the log. Please check whether your apk/apks files are complete.

**Comment by Sudhanshu074w** [comment]
The apk/apks which I'm trying to install are completely fine. I can install then using the system package installer, InstallerX and SAI, but not from PI 🥲.

**Comment by Sudhanshu074w** [comment]
So, the issue is in the latest build ig, because I tried older builds and it is working.

**Comment by SanmerDev** [comment]
@Sudhanshu074w Try this [PI-0.3.8.dev.896de14-208-release](https://github.com/SanmerApps/PI/actions/runs/8858086959/artifacts/1453077641)
> Might not fix the bug, but add more logging so problems can be found

**Comment by Sudhanshu074w** [comment]
Yeah, it's working ! Thankyou so much sir.
