### ISSUE TITLE
Invalid in Chinese firmware for OPPO/OnePlus/realme devices

### ISSUE THREAD

**Issue by cherinyy** [SanmerApps/PI#97]
OPPO/OnePlus/realme uses a modified package installer in the Chinese firmware.

The most typical issue is that it fails to install Android App Bundle apps and this is intentional.

So if it wants to take effect, I'm guessing that `PI` needs to do the installation itself, rather than calling the package installer that comes with the firmware, which I don't know if that's normal or not. I'm using Shizuku mode.

Meanwhile, `SAI` and `MiXplorer` were able to install the apps themselves via Shizuku without any problems, so I'm sure there's no problem there.

![Screenshot_2024-06-05-20-58-12-71_708f76cdf2c7449ff16a8486e0e036f6](https://github.com/SanmerApps/PI/assets/9050713/1ab8fef9-ea4a-4008-9221-952f25ef907c)

![Screenshot_2024-06-05-20-58-22-92_708f76cdf2c7449ff16a8486e0e036f6](https://github.com/SanmerApps/PI/assets/9050713/d8950bbf-9261-42e2-9e1f-e047779a7c4b)

If I need to provide some sort of log to fix the problem, please do tell me what to do, thanks.

**Comment by SanmerDev** [comment]
Please provide logs
> Start capturing from app launch until the end of apk installation

**Comment by SanmerDev** [comment]
It depends on you
- [Adb](https://developer.android.com/tools/releases/platform-tools)
- [LogFox](https://github.com/F0x1d/LogFox)
- Other you like

**Comment by cherinyy** [comment]
[06_06-21-38-50_573.zip](https://github.com/user-attachments/files/15630407/06_06-21-38-50_573.zip)

**Comment by SanmerDev** [comment]
I have no idea about this, and I don't have an OPPO/OnePlus/Realme device so I won't consider fixing it.
